name: Gospo Collective
favicon: null
layout_spectrum: 0.3135133010800928
typography_spectrum: 0.9363446568604559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8342960791196674
  lightness: 0.23402436380274594
  saturation: 0.5540577392093837
  rhythmicContrast: 0.15933725493960083
purpose: []
