name: Gospo Collective
favicon: null
layout_spectrum: 0.3135133010800928
typography_spectrum: 0.4371
title: Gospo Collective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-56126578-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#000000'
    - '#69737e'
    - '#ff3426'
    - '#0042c4'
  brandStrength: 0.8342960791196674
  lightness: 0.23402436380274594
  saturation: 0.5540577392093837
  rhythmicContrast: 0.15933725493960083
purpose: []
